server:
  http_listen_port: 9080
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: "default"    # <- establece el org id que Loki espera
    batchwait: 1s
    timeout: 10s
scrape_configs:
  - job_name: application-logs
    static_configs:
      - labels:
          job: application-logs
          __path__: /var/log/metamapa/**/*.log
